### ISSUE TITLE
JOSS submission checklist

### ISSUE THREAD

**Issue by agitter** [gitter-lab/prmf#2]
This issue is a master checklist tracking progress on our Journal of Open Source Software submission.  It combines the JOSS [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html),  [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html), and our own best practices.
- [x] Prepare package for release to PyPI (#8)
- [ ] Add API documentation (#6)
- [ ] Move Manubot deploy script to repository and attribute (#10)
- [ ] Document install instructions and example usage
- [x] Add test cases for expected results on simulated data and enable Travis CI testing (#5)
- [ ] Set up release archiving with Zenodo (#4)
- [ ] Write short manuscript with statement of need, core features, related work, acknowledgements (#7)
- [ ] Add community guidelines for support or contributions
- [ ] Add JOSS software metadata file

We can expand this checklist as needed and update it to cross-reference the relevant individual issues.
