### ISSUE TITLE
Methods and example usage checklist

### ISSUE THREAD

**Issue by agitter** [gitter-lab/prmf#3]
In addition to the required items before JOSS submission (#2), there are other optional methods and analyses that we may include in the manuscript or repository:
- [ ] Description of algorithm (pseudocode) and optimization (objective function, equations)
- [ ] Scripts or automated pipeline to analyze simulated data
- [ ] Example results on simulated data, run PRMF and related methods on the same simulated data
- [ ] Example results for PRMF analysis of recount2 data
